#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <math.h>
#include <time.h>
#include <linux/types.h>
#include <fcntl.h>
#include <unistd.h>
#include <errno.h>

#include "fat12.h"



int fid; /* global variable set by the open() function */




int main(int argc, char *argv[])
{

	if (argc != 2)
	{
		printf("Usage: %s <floppy_image>\n", argv[0]);
		exit(1);
	}

	if ( (fid = open (argv[1],  O_RDWR|O_CREAT))  < 0 )
	{
		perror("Error: ");
		return -1;
	}

	
	/* See fat12.pdf for layout details */
	
	// Step 1. Create floppy.img with the school solution. Read the values 
	// from the boot sector of the floppy.img and initialize boot sector
	// with those values. If you read bootsector of the floppy.img correctly,
	// the values will be:
	
        boot_record_t boot;
	boot.sector_size = 512 ;
	boot.sectors_per_cluster=  1 ;
	boot.reserved_sector_count=  1;
	boot.number_of_fats=  2;
	boot.number_of_dirents=  224;
	boot.sector_count=  2880 ;
	boot.media_type=  0xf0;
	boot.fat_size_sectors=  9;
	boot.sectors_per_track=  18;
	boot.nheads=  2;
	boot.sectors_hidden=  0;
	boot.sector_count_large=  0; 
	
	// boot_record_t boot;
        // if (read(fid, &boot, sizeof (boot)) > 0){
	// printf("sector_size: %d\n", boot.sector_size);
	// printf("sectors_per_cluster: %d\n", boot.sectors_per_cluster);
	// printf("reserved_sector_count: %d\n", boot.reserved_sector_count);
	// printf("number_of_fats: %d\n", boot.number_of_fats);
	// printf("number_of_dirents: %d\n", boot.number_of_dirents);
        // printf("sector_count: %d\n", boot.sector_count);
	// }
        // etc ...
	

	
	// Step 2. Zero FAT1 and FAT2 tables according to the fat12.pdf. 
        char buf[512];

memset(buf,'\0',512);
memcpy(buf, &boot, sizeof(boot));
write(fid, buf, 512);

        int i = 0;
        for (i = 1; i <= 2880; i++){
            memset(buf,'\0',512);
            write(fid, buf, 512);
        }
/*
        fat_dirent_t dir;
        read(fid, &dir, sizeof(dir));
        printf("name: %d %c\n", dir.name[0], dir.name[0] == 0xe5);
        printf("ext: %s\n", dir.ext);
        printf("l_first_cluster: %d\n", dir.l_first_cluster);
*/	
        
	// Step 3. Set direntries as free according to the fat12.pdf. 
	
	// Step 4. Handle data block (e.g you can zero them or just leave 
	// untouched. What are the pros/cons?)
	
	// For steps 2-3, you can also read the sectors from the image that was 
	// generated by the school solution if not sure what should be the values.
	
	
	close(fid);
	return 0;
}

